### ISSUE TITLE
error:03000086:digital envelope routines::initialization error

### ISSUE THREAD

**Issue by AaronNGray** [AaronNGray/react-toolkit-example#1]
```
C:\Users\aaron\Test\react-toolkit-example\test-app>yarn dev
yarn run v1.22.19
$ react-toolkit dev
(node:9092) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
 10% building modules 1/1 modules 0 activei ｢wds｣: Project is running at http://127.0.0.1:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to /index.html
 10% building modules 1/3 modules 2 active ...\node_modules\webpack\hot\dev-server.jsnode:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\aaron\Test\react-toolkit-example\test-app\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\aaron\Test\react-toolkit-example\test-app\node_modules\webpack\lib\NormalModule.js:386:16)
    at handleParseError (C:\Users\aaron\Test\react-toolkit-example\test-app\node_modules\webpack\lib\NormalModule.js:434:10)
    at C:\Users\aaron\Test\react-toolkit-example\test-app\node_modules\webpack\lib\NormalModule.js:466:5
    at C:\Users\aaron\Test\react-toolkit-example\test-app\node_modules\webpack\lib\NormalModule.js:327:12
    at C:\Users\aaron\Test\react-toolkit-example\test-app\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (C:\Users\aaron\Test\react-toolkit-example\test-app\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at Array.<anonymous> (C:\Users\aaron\Test\react-toolkit-example\test-app\node_modules\loader-runner\lib\LoaderRunner.js:202:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by AaronNGray** [comment]
Temporary fix :-
```
set NODE_OPTIONS=--openssl-legacy-provider
```
